# taplo wants to reorder commands in alphabetical order, but order is important here
exclude = ["Cross.toml"]

[[rule]]

[rule.formatting]
indent_string = "    "
reorder_arrays = true
reorder_keys = true
