[package]
name = "bpfman-kernel"
description = "Backend-independent kernel observation capabilities"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
bpfman-model.workspace = true
bpfman-fs.workspace = true
thiserror.workspace = true
