[package]
name = "bpfman-store-sqlite"
description = "Initialisation and access to the Go bpfman SQLite schema"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
tracing.workspace = true
bpfman-store.workspace = true
base64.workspace = true
chrono.workspace = true
bpfman-core.workspace = true
bpfman-fs.workspace = true
bpfman-model.workspace = true
rusqlite.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tempfile.workspace = true

[dev-dependencies]
bpfman-lock.workspace = true
