name: bpfman-docs

on: # yamllint disable-line rule:truthy
  push:
    branches: [main]
    tags:
      - v*

jobs:
  build-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - uses: actions/setup-go@v5
        with:
          # prettier-ignore
          go-version: '1.21' # yamllint disable-line rule:quoted-strings
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build API docs
        run: |
          ./scripts/api-docs/generate.sh apidocs.html

      - name: Configure Git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Deploy Docs (Release Version)
        if: startsWith(github.ref_name, 'v')
        run: |
          mike deploy --push --update-aliases ${{ github.ref_name }} latest

      - name: Deploy Docs (Development Version)
        if: github.ref_name == 'main'
        run: |
          mike deploy --push main
